### ISSUE TITLE
Germanet initialization fails on windows with regex error

### ISSUE THREAD

**Issue by Domattee** [Germanet-sfs/GermaNetApi#9]
Trying to create a new GermaNet instance with a File Object or String path fails due to a regex error.

GermaNet gnet = new GermaNet("some/path/GN_V140.zip");

fails on Windows 10 with 
Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1

	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1789)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.split(String.java:2354)
	at java.base/java.lang.String.split(String.java:2401)
	at de.tuebingen.uni.sfs.germanet.api.GermaNet.<init>(GermaNet.java:302)
	at de.tuebingen.uni.sfs.germanet.api.GermaNet.<init>(GermaNet.java:242)
	...

Looking at the relevant section in GermaNet.java we see:
                if (name.split(File.separator).length > 1) {
                    name = name.split(File.separator)[name.split(File.separator).length - 1];
                }

name.split(File.separator) fails on windows as the file separator character is a single backslash, which is not a legal regex. Changing the separator on the input string does not fix this issue.

There must be some extra component to this error, as this issue does not occur on all of my windows machines, although the line _should_ fail. I think using Files builtin path splitting should fix this:
		name = new File(name).getName()
Alternatively the file separator could be escaped to be valid regex.

**Comment by m-hinrichs** [comment]
It looks like you are loading the GermaNet data from a zip file. We will fix this bug, but in the meantime it should work if you unzip the file and load the data from the folder.

**Comment by Domattee** [comment]
Thanks for the update and the workaround!
